# SPDX-FileCopyrightText: Amutable GmbH <https://amutable.com/>
# SPDX-License-Identifier: MPL-2.0

"""Terminal image-output format drivers."""

load("//box:test.bzl", "box_python_test")
load("//python:defs.bzl", "tine_python_binary", "tine_python_library")

tine_python_binary(
    name = "archive",
    main = "archive.py",
    deps = [
        "//:specs",
        "//:util",
        "//archive:cpio",
        "//archive:tar",
        "//image:finalize",
    ],
    visibility = ["PUBLIC"],
)

tine_python_binary(
    name = "disk",
    main = "disk.py",
    deps = [
        ":repart",
        "//:specs",
        "//:util",
        "//image:finalize",
        "//image:manifest-lib",
    ],
    visibility = ["PUBLIC"],
)

tine_python_library(
    name = "repart",
    srcs = ["repart.py"],
    deps = ["//:util"],
)

tine_python_binary(
    name = "convert",
    main = "convert.py",
    deps = ["//:specs", "//:util"],
    visibility = ["PUBLIC"],
)

tine_python_binary(
    name = "sysext",
    main = "sysext.py",
    deps = [
        ":repart",
        "//:specs",
        "//:util",
        "//image:finalize",
        "//image:manifest-lib",
        "//rootfs:rootfs",
    ],
    visibility = ["PUBLIC"],
)

box_python_test(
    name = "test",
    box = "//tools:dev.box",
    srcs = [
        "disk.py",
        "disk_test.py",
        "repart_test.py",
    ],
    deps = [
        ":repart",
        "//:specs",
        "//:util",
        "//image:finalize",
        "//image:manifest-lib",
    ],
)
