# SPDX-FileCopyrightText: Amutable GmbH <https://amutable.com/>
# SPDX-License-Identifier: MPL-2.0

"""Pinned execution-environment launcher."""

load("//python:defs.bzl", "tine_python_binary", "tine_python_library")
load(":test.bzl", "box_python_test")

tine_python_library(
    name = "isolation",
    srcs = ["isolation.py"],
    visibility = ["tine//..."],
)

tine_python_binary(
    name = "sandbox",
    main = "sandbox.py",
    deps = [":isolation"],
    visibility = ["PUBLIC"],
)

box_python_test(
    name = "test",
    box = "//tools:dev.box",
    srcs = [
        "isolation_test.py",
        "sandbox.py",
        "sandbox_test.py",
    ],
    deps = [":isolation"],
)
