# SPDX-FileCopyrightText: Amutable GmbH <https://amutable.com/>
# SPDX-License-Identifier: MPL-2.0

"""Target-root and stored-layer filesystem primitives."""

load("//box:test.bzl", "box_python_test")
load("//python:defs.bzl", "tine_python_library")

tine_python_library(
    name = "rootfs",
    srcs = ["rootfs.py"],
    deps = ["//box:isolation"],
    visibility = ["tine//..."],
)

box_python_test(
    name = "test",
    box = "tine//tools:dev.box",
    srcs = ["rootfs_test.py"],
    deps = [":rootfs"],
)
