#!/bin/sh

# SPDX-FileCopyrightText: Amutable GmbH <https://amutable.com/>
# SPDX-License-Identifier: MPL-2.0

set -eu

cell=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$cell"
exec "$cell/bin/tine" buck run tine//tools:ty-editor -- "$@"
