# SPDX-FileCopyrightText: Amutable GmbH <https://amutable.com/>
# SPDX-License-Identifier: MPL-2.0

"""Native package systems, repositories, releases, managers, and buildroots."""

load("//box:test.bzl", "box_python_test")
load("//python:defs.bzl", "tine_python_library")

tine_python_library(
    name = "href",
    srcs = ["href.py"],
    visibility = ["PUBLIC"],
    deps = ["//:util"],
)

tine_python_library(
    name = "extractor",
    srcs = ["extractor.py"],
    visibility = ["PUBLIC"],
    deps = ["//:specs", "//:util", "//rootfs:rootfs"],
)

tine_python_library(
    name = "installer",
    srcs = ["installer.py"],
    deps = ["//:specs", "//:util", "//rootfs:rootfs"],
    visibility = ["PUBLIC"],
)

tine_python_library(
    name = "snapshotter",
    srcs = ["snapshotter.py"],
    deps = ["//:specs", "//:util"],
    visibility = ["PUBLIC"],
)

tine_python_library(
    name = "transaction",
    srcs = ["transaction.py"],
    deps = [":snapshotter", "//:util"],
    visibility = ["PUBLIC"],
)

box_python_test(
    name = "test",
    box = "tine//catalog:fedora.rawhide.box",
    srcs = ["installer_test.py", "transaction_test.py"],
    deps = [":installer", ":transaction"],
)
